AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PG&E Coding Challenge

 
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    MemorySize: 128

Resources:
  APIFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: function.lambdaHandler
      Runtime: nodejs14.x
      Timeout: 10
      Events:
        StationData:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: "/generate_data"
            Method: POST
      Environment:
        Variables:
          BUCKET_NAME: pg-e-nathan-coding-challenge
          FILE_NAME: stations.csv
          REGION: us-east-2
